### ISSUE TITLE
Iron Doors do not open by themselves

### ISSUE THREAD

**Issue by Vladg24YT** [Vladg24YT/LilyBukkit#15]
Iron doors open only when you right click them after providing a greenstone signal, unless you open it with a greenstone torch.

**Comment by MIOGMIOG** [comment]
This issue is also with redstone (greenstone) - also I experienced this issue on Erdbeers server (which is on modified Smaeds jar - probably)
Also this is not LilyBukkit issue, but Smaeds jar or Rosepad issue.

**Comment by Vladg24YT** [comment]
Closing the issue as it is not LilyBukkit's fault.
