### ISSUE TITLE
Blocks disappear when placed and can't be broken

### ISSUE THREAD

**Issue by Vladg24YT** [Vladg24YT/LilyBukkit#25]
The title says it all.

**Comment by MIOGMIOG** [comment]
I can confirm this, I have noticed this bug as well.

**Comment by MIOGMIOG** [comment]
@Vladg24YT I guess you misunderstood what the "invalid" tag means, the invalid tag is given if the issue makes no sense at all, or the issue is not related to the project at all and not that something is wrong, this issue makes sense, even I noticed this problem.
